#!/usr/bin/python
from task_handler import TaskHandler
from console_handler import ConsoleHandler

if __name__ == '__main__':
    console = ConsoleHandler()
    console_command, console_arguments = console.parse_cli()
    task_handler = TaskHandler()
    
    match console_command:
        case 'list':
            task_handler.get_tasklist(console_arguments[0])
        case 'add':
            task_handler.create_task(console_arguments)
        case 'update':
            task_handler.update_task(int(console_arguments[0]), console_arguments[1::])
        case 'delete':
            task_handler.delete_task(console_arguments) 
